# Generated by Django 6.0.1 on 2026-01-28 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_demandforecast_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grn', to='base.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='received_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
