# Generated by Django 6.0.1 on 2026-01-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_goodsreceivednote_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
